#!/bin/sh

# Resources:
#
# - https://git.sr.ht/~sircmpwn/dotfiles/tree/master/item/bin/sway-run
# - https://github.com/luispabon/sway-dotfiles/blob/master/ssway

export TERM=alacritty

# Force firefox into wayland and enable hw video decoding (ff 75+)
export MOZ_ENABLE_WAYLAND=1
export MOZ_WAYLAND_USE_VAAPI=1

# QT apps theme
export QT_QPA_PLATFORMTHEME=qt5ct

# Fixes issues on jetbrains ides
export _JAVA_AWT_WM_NONREPARENTING=1

export XDG_SESSION_TYPE=wayland
export XDG_DESKTOP_DIR="$HOME"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/pics"
export XDG_VIDEOS_DIR="$HOME/videos"

exec sway
