# See fuzzel.ini(5) for the full reference.

font=monospace:size=12
dpi-aware=no
width=50
lines=15
horizontal-pad=20
vertical-pad=10
inner-pad=10
prompt=">   "
icon-theme=Adwaita
icons-enabled=yes
fuzzy=yes
terminal=foot

[colors]
background=282828d9
text=ebdbb2ff
match=66ccffff
selection=555555ff
selection-text=ebdbb2ff
selection-match=66ccffff
border=00000000

[border]
width=0
radius=0
